name: Publish Package
on:
  push:
    branches:
      - master
permissions:
  id-token: write # Required for npm OIDC
  contents: write # Required for bumping tag
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run fmt
      - run: bun test
      - run: bun run build
      - run: ./bump-and-publish.sh
