name: Publish Package
on:
  push:
    tags:
      - v*
permissions:
  id-token: write # Required for npm OIDC
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun ci
      - run: bun run build
      - run: bun test
      - run: bun run fmt
      - run: bunx npm@latest publish
