name: Publish Package
on:
  push:
    branches:
      - master
permissions:
  id-token: write # npm OIDC
  contents: write # push tags
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: bun ci
      - run: bun run build
      - run: bun test
      - run: bun run fmt
      - run: ./publish.sh
