name: Publish Package
on:
  push:
    tags:
      - v*
    branches:
      - master
permissions:
  id-token: write # npm OIDC
  contents: write # push tags
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: echo "${{ github.event_name }}"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # whole history needed for potential tag bump
      - uses: oven-sh/setup-bun@v2
      - run: bun ci
      - run: bun run build
      - run: bun test
      - run: bun run fmt
      - run: ./publish.sh
